using Plots; plotly()
m = 30; n = 20; X = Float64.([(x-m/4)^2+(y-n/3)^2 < 5^2 for x=1:m, y=1:n])
dfdx = diff(X,1)
dfdy = diff(X,2)
heatmap(1:m, 1:n, X.'); title!("f(x,y)")
heatmap(1:m, 1:n, dfdx.'); title!("df(x,y) / dx")
heatmap(1:m, 1:n, dfdy.'); title!("df(x,y) / dy")
xlabel!("x")
ylabel!("y")
